# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='dfvfs/proto/transmission.proto',
  package='transmission',
  serialized_pb='\n\x1edfvfs/proto/transmission.proto\x12\x0ctransmission\"\x84\x02\n\x08PathSpec\x12&\n\x06parent\x18\x01 \x01(\x0b\x32\x16.transmission.PathSpec\x12\x16\n\x0etype_indicator\x18\x02 \x02(\t\x12\x1a\n\x12\x63ompression_method\x18\x03 \x01(\t\x12\x12\n\nidentifier\x18\x04 \x01(\t\x12\r\n\x05inode\x18\x05 \x01(\x04\x12\x10\n\x08location\x18\x06 \x01(\t\x12\x12\n\npart_index\x18\x07 \x01(\x05\x12\x14\n\x0crange_offset\x18\x08 \x01(\x04\x12\x12\n\nrange_size\x18\t \x01(\x04\x12\x14\n\x0cstart_offset\x18\n \x01(\x04\x12\x13\n\x0bstore_index\x18\x0b \x01(\x05')




_PATHSPEC = descriptor.Descriptor(
  name='PathSpec',
  full_name='transmission.PathSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='parent', full_name='transmission.PathSpec.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type_indicator', full_name='transmission.PathSpec.type_indicator', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='compression_method', full_name='transmission.PathSpec.compression_method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='identifier', full_name='transmission.PathSpec.identifier', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inode', full_name='transmission.PathSpec.inode', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location', full_name='transmission.PathSpec.location', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='part_index', full_name='transmission.PathSpec.part_index', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='range_offset', full_name='transmission.PathSpec.range_offset', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='range_size', full_name='transmission.PathSpec.range_size', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start_offset', full_name='transmission.PathSpec.start_offset', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='store_index', full_name='transmission.PathSpec.store_index', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=309,
)

_PATHSPEC.fields_by_name['parent'].message_type = _PATHSPEC
DESCRIPTOR.message_types_by_name['PathSpec'] = _PATHSPEC

class PathSpec(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PATHSPEC
  
  # @@protoc_insertion_point(class_scope:transmission.PathSpec)

# @@protoc_insertion_point(module_scope)
