# Run tox tests on Ubuntu Docker images using GIFT PPA
name: test_tox
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - python-version: '3.6'
          toxenv: 'py36'
        - python-version: '3.7'
          toxenv: 'py37'
        - python-version: '3.8'
          toxenv: 'py38,coverage,codecov'
        - python-version: '3.9'
          toxenv: 'py39'
        - python-version: '3.10'
          toxenv: 'py310'
        - python-version: '3.8'
          toxenv: 'pylint'
        - python-version: '3.8'
          toxenv: 'docs'
    container:
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up container
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update -q
        apt-get install -y libterm-readline-gnu-perl locales software-properties-common
        locale-gen en_US.UTF-8
        ln -f -s /usr/share/zoneinfo/UTC /etc/localtime
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        add-apt-repository -y universe
        add-apt-repository -y ppa:deadsnakes/ppa
        add-apt-repository -y ppa:gift/dev
        apt-get update -q
        apt-get install -y build-essential git libffi-dev python${{ matrix.python-version }} python${{ matrix.python-version }}-dev python${{ matrix.python-version }}-venv libbde-python3 libewf-python3 libfsapfs-python3 libfsext-python3 libfshfs-python3 libfsntfs-python3 libfsxfs-python3 libfvde-python3 libfwnt-python3 libluksde-python3 libmodi-python3 libqcow-python3 libsigscan-python3 libsmdev-python3 libsmraw-python3 libvhdi-python3 libvmdk-python3 libvsgpt-python3 libvshadow-python3 libvslvm-python3 python3-cffi-backend python3-cryptography python3-dfdatetime python3-distutils python3-dtfabric python3-idna python3-mock python3-pbr python3-pip python3-pytsk3 python3-pyxattr python3-setuptools python3-six python3-yaml
    - name: Install tox
      run: |
        python3 -m pip install tox
    - name: Run tests
      env:
        LANG: en_US.UTF-8
      run: |
        tox -e${{ matrix.toxenv }}
